OPENAI_API_KEY = "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"
EMAIL_SENDER = "pdfsummarizerai@gmail.com"
EMAIL_PASSWORD = "iabb ejta nyip mxal"
